FROM registry.redhat.io/ansible-automation-platform-26/de-supported-rhel9:latest

RUN pip3 install --user aiohttp aiohttp-retry --quiet

# EDA looks for event sources at extensions/eda/plugins/event_source/
COPY collection \
  /usr/share/ansible/collections/ansible_collections/abreu/loadshedding

# Create the extensions path and symlink the plugin there
RUN mkdir -p /usr/share/ansible/collections/ansible_collections/abreu/loadshedding/extensions/eda/plugins/event_source && \
    cp /usr/share/ansible/collections/ansible_collections/abreu/loadshedding/plugins/event_source/eskomsepush_source.py \
       /usr/share/ansible/collections/ansible_collections/abreu/loadshedding/extensions/eda/plugins/event_source/
