apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno-spoke
  namespace: home
  labels:
    infraenvs.agent-install.openshift.io: home
    cluster.open-cluster-management.io/backup: "true"
  annotations:
    bmac.agent-install.openshift.io/hostname: sno-spoke

spec:
  architecture: x86_64
  automatedCleaningMode: disabled

  bmc:
    address: redfish-virtualmedia://XXXXXXXXXX:8000/redfish/v1/Systems/"here it is your vm id"
    credentialsName: sno-spoke-bmc-secret
    disableCertificateVerification: true

  bootMACAddress: "XXXXXXXXXX"

  customDeploy:
    method: start_assisted_install

  rootDeviceHints:
    deviceName: /dev/vda

  online: false
