---
- name: Search EskomSePush Areas
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    esp_token: "XXXXXXXXXX"
    search_term: "stellenbosch"

  tasks:
    - name: Search for Area ID
      ansible.builtin.uri:
        url: "https://developer.sepush.co.za/business/2.0/areas_search?text={{ search_term }}"
        method: GET
        headers:
          token: "{{ esp_token }}"
        return_content: yes
      register: search_results

    - name: Display Search Results
      ansible.builtin.debug:
        msg: "{{ search_results.json.areas }}"

    - name: Help Message
      ansible.builtin.debug:
        msg: "Look for the 'id' field in the list above and copy it for your poller playbook."
