---
- name: Test - EskomSePush
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    esp_token: "XXXXXXXXXX"
    area_id: "eskme-2-stellenboschstellenboschwesterncape"
    #test_mode: "current"
    test_mode: "future" # Change from "current" to "future"

  tasks:
    - name: Query EskomSePush API
      ansible.builtin.uri:
        url: "https://developer.sepush.co.za/business/2.0/area?id={{ area_id }}{{ '&test=' + test_mode if test_mode != '' else '' }}"
        method: GET
        headers:
          token: "{{ esp_token }}"
        return_content: yes
      register: esp_api_response

    - name: Calculate Power Status
      ansible.builtin.set_fact:
        # Check if any event is active right now (UTC+2) SAST
        outage_active: >-
          {{
            esp_api_response.json.events | selectattr('start', 'le', now(fmt='%Y-%m-%dT%H:%M:%S+02:00'))
            | selectattr('end', 'ge', now(fmt='%Y-%m-%dT%H:%M:%S+02:00'))
            | list | length > 0
          }}

    - name: Results
      ansible.builtin.debug:
        msg:
          - "Area: {{ esp_api_response.json.info.name }}"
          - "Status: {{ 'SHUTDOWN REQUIRED' if outage_active else 'SHUTDOWN NOT REQUIRED' }}"
          - "Event Count: {{ esp_api_response.json.events | length }}"
